[package]
name = "wootili-view"
version = "0.6.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wooting-rgb-sys = "0.3.2"
eframe = "0.27.2"
image = "0.25.1"
xcap = "0.0.9"
egui-notify = "0.14.0"
lazy_static = "1.4.0"
scorched = "0.5.3"
serde = { version = "1.0.201", features = ["derive"] }
ron = "0.8.1"
ver-cmp = "0.1.4"
libloading = "0.8.3"
