[package]
name = "wootili-view"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wooting-rgb-sys = "0.3.2"
eframe = "0.28.1"
image = "0.25.1"
xcap = "0.0.10"
egui-notify = "0.15.0"
lazy_static = "1.5.0"
scorched = "0.5.3"
serde = { version = "1.0.204", features = ["derive"] }
ron = "0.8.1"
ver-cmp = "0.1.4"
libloading = "0.8.4"
