[package]
name = "wootili-view"
version = "0.3.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wooting-rgb-sys = "0.3.0"
screenshots = "0.8.6"
image = "0.24.8"
eframe = "0.25.0"
once_cell = "1.19.0"
egui-notify = "0.12.0"