[package]
name = "wootili-view"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wooting-rgb-sys = "0.3.0"
eframe = "0.25.0"
image = "0.24.8"
xcap = "0.0.3"
egui-notify = "0.12.0"
lazy_static = "1.4.0"
scorched = "0.5.1"
reqwest = { version = "0.11.24", features = ["blocking"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
ron = "0.8.1"